### PR TITLE
Fixes #23 by bumping the max idle connections per host

### LINKED ISSUE #23: Find out why so many time_wait connections being created
To reproduce:

1. ssh s61901cnt72.sc.couchbase.com (perf VM)
1. Run sgload:

```
sgload gateload --createreaders --createwriters --numreaders 100 --numupdaters 100 --numwriters 100 --numrevsperdoc 2 --numdocs 500000 --numchannels 10 --batchsize 50  --sg-url http://s61705cnt72.sc.couchbase.com:4984/db/
```

1. In another terminal, ssh into the same box and run `netstat -n | grep -i 4984 | wc -l` and the number of connections will be skyrocketing towards 30K.  Note that `netstat -n | grep -i 4984 | grep -i time_wait | wc -l` return the majority

### PR DESCRIPTION
**Pull request by tleyden**
Fixes #23 

I wrote up a [blog post](http://tleyden.github.io/blog/2016/11/21/tuning-the-go-http-client-library-for-load-testing/) to try to explain the problem and repro in a simple test case.

### CODE REVIEW

File: sgload/sg_datastore.go [hunk 1]
```diff
@@ -456,3 +463,22 @@ func timeDeltaPerDocument(numDocs int, timeDeltaAllDocs time.Duration) time.Dura
...
 }
+
+func getHttpClient() *http.Client {
+	// return http.DefaultClient
+	return sgClient
+}
+
+func customDefaultTransportWithConnPool(numConnections int) *http.Transport {
+	// Customize the Transport to have larger connection pool
+	defaultRoundTripper := http.DefaultTransport
```
Comment (ajres) [inline sgload/sg_datastore.go]: defaultRoundTripper variable name seems a bit out of place in this context.

**Comment by tleyden** [comment]
@ajres ok I pushed up some changes.
